In [17]:
from __future__ import unicode_literals

# Importing the libraries
import numpy as np
import pandas as pd

# from sklearn import preprocessing
from sklearn.preprocessing import Imputer

# 1. Reading our pandas dataframes inputs variables

We read our latest 12 weeks life plants input datasets **Phreatic Level, Precipitations, Temperature, Luminosity, Direction and Wind Speed** from May 5th to August 3rd to cover the last 12 weeks of the plant's life (the last 12 of the 28 weeks) which is the time range in which the banana bunch/cluster is formed.


## 1.1. Wind Direction - Testing dataset 

In [18]:
wind_direction_l12w_testing = pd.read_csv('../data/processed/WindDirection/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Wind-Direction-TESTING_May-4_August-03_2018_DummiesValues.csv', )

In [19]:
print(wind_direction_l12w_testing.shape)
wind_direction_l12w_testing.head(10)

(880, 8)


E  N  NE  NO  O  S  SE  SO
0  0  0   0   0  0  1   0   0
1  0  0   0   0  0  1   0   0
2  0  0   0   0  0  1   0   0
3  0  0   0   1  0  0   0   0
4  0  0   0   0  0  1   0   0
5  0  0   0   1  0  0   0   0
6  0  0   0   0  0  1   0   0
7  1  0   0   0  0  0   0   0
8  0  0   0   0  0  1   0   0
9  1  0   0   0  0  0   0   0

## 1.2. Luminosity - Testing dataset 

In [20]:
luminosity_l12w_testing = pd.read_csv('../data/processed/Luminosity/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Luminosity_Normalized_TESTING_May-4_August-03.csv', )

In [21]:
print(luminosity_l12w_testing.shape)
luminosity_l12w_testing.head(10)

(880, 1)


Luz (lux)
0   0.000000
1   0.033142
2   0.000000
3   0.000000
4   0.000000
5   0.470816
6   0.924321
7   0.384545
8   0.000000
9   0.402236

## 1.3. Phreatic Level - Testing dataset 

In [22]:
phreatic_level_l12w_testing = pd.read_csv('../data/processed/PhreaticLevel/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Phreatic-Level_Normalized_TESTING_May-4_August-03.csv', )

In [23]:
print(phreatic_level_l12w_testing.shape)
phreatic_level_l12w_testing.head(10)

(446, 25)


PORVL2N1  PORVL2N2  PORVL4N1  PORVL5N1  PORVL6N1  PORVL7N1  PORVL8N1  \
0  0.604651  0.512821  0.639535  0.488636  0.805970  0.281481  0.591304   
1  0.860465  0.803419  0.941860  0.511364  0.223881  0.866667  0.973913   
2  0.779070  0.709402  0.883721  0.727273  0.977612  0.718519  0.834783   
3  0.790698  0.615385  0.883721  0.727273  1.000000  0.740741  0.886957   
4  0.790698  0.991453  0.872093  0.806818  0.791045  0.733333  0.852174   
5  0.790698  0.735043  0.895349  0.772727  0.985075  0.762963  0.869565   
6  0.651163  0.632479  0.767442  0.661003  0.799005  0.525926  0.721739   
7  0.511628  0.752137  0.279070  0.556818  0.791045  0.777778  0.895652   
8  0.848837  0.606838  0.883721  0.727273  1.000000  0.807407  0.886957   
9  0.825581  0.735043  0.895349  0.886364  1.000000  0.807407  0.913043   

   PORVL9N1  PORVL10N1  PORVL13N1    ...      PORVL18N2  PORVL18N3  PORVL18N4  \
0  0.442105   0.377778   0.640351    ...       0.487805   0.361905   0.670588   
1  0.800000   0.988889   0.956140    ...       0.804878   0.771429   0.552941   
2  0.642105   0.611111   0.842105    ...       0.674797   0.685714   0.823529   
3  0.863158   0.644444   0.798246    ...       0.642276   0.771429   0.835294   
4  0.673684   0.622222   0.833333    ...       0.707317   0.876190   0.717647   
5  0.684211   0.655556   0.885965    ...       0.699187   0.714286   0.835294   
6  0.536842   0.444444   0.719298    ...       0.569106   0.647954   0.699175   
7  0.684211   0.766667   0.745614    ...       0.398374   0.638095   0.741176   
8  0.894737   0.722222   0.868421    ...       0.707317   0.685714   0.741176   
9  0.715789   0.866667   0.929825    ...       0.739837   0.847619   0.894118   

   PORVL21N1  PORVL21N2  PORVL21N3  PORVL21N4  PORVL21N5  PORVL24N1  PORVL24N2  
0   0.447059   0.719626   0.685714   0.540984   0.644231   0.321429   0.000000  
1   0.764706   0.682243   0.704762   0.598361   0.846154   0.901786   0.935185  
2   0.576471   0.906542   0.771429   0.803279   0.711538   0.616071   0.787037  
3   0.623529   0.906542   0.828571   0.754098   0.807692   0.660714   0.805556  
4   0.717647   0.570093   0.638095   0.786885   0.721154   0.767857   0.787037  
5   0.670588   0.915888   0.819048   0.762295   0.759615   0.660714   0.833333  
6   0.647059   0.793048   0.674183   0.631664   0.528846   0.589286   0.490741  
7   0.447059   1.000000   0.704762   0.614754   0.759615   0.196429   0.833333  
8   0.764706   0.915888   0.838095   0.811475   0.855769   0.991071   0.833333  
9   0.729412   0.794393   0.847619   0.762295   0.759615   0.741071   0.898148  

[10 rows x 25 columns]

## 1.4. Precipitations - Testing dataset 

In [27]:
precipitations_l12w_testing = pd.read_csv('../data/processed/Precipitations/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Precipitations_Normalized_TESTING_May-4_August-03_2018.csv', )

In [28]:
print(precipitations_l12w_testing.shape)
precipitations_l12w_testing.head(10)

(880, 1)


Precipitación (ml)
0                 0.0
1                 0.0
2                 0.0
3                 0.0
4                 0.0
5                 0.0
6                 0.0
7                 0.0
8                 0.0
9                 0.0

## 1.5. Temperatura - Testing dataset 

In [31]:
temperature_l12w_testing = pd.read_csv('../data/processed/Temperature/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Temperature_Normalized_TESTING_May-4_August-03_2018.csv', )

In [32]:
print(temperature_l12w_testing.shape)
temperature_l12w_testing.head(10)

(880, 1)


Temperatura (C)
0         0.045480
1         0.241999
2         0.171814
3         0.687816
4         0.895003
5         0.154408
6         0.203257
7         0.498035
8         0.701853
9         0.410444

## 1.6. Wind Speed - Testing dataset 

In [34]:
wind_speed_l12w_testing = pd.read_csv('../data/processed/WindSpeed/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Wind-Speed_Normalized_TESTING_May-4_August-03_2018.csv', )

In [35]:
print(wind_speed_l12w_testing.shape)
wind_speed_l12w_testing.head(10)

(880, 1)


Velocidad del viento (Km/h)
0                     0.121387
1                     0.027815
2                     0.017471
3                     0.016854
4                     0.000000
5                     0.063253
6                     0.000000
7                     0.017270
8                     0.033546
9                     0.000000

## 1.7. Banana - Cluster weight 

Cluster weight training data of one week of productivity taken as a baseline is loaded.

The week is from July 27th to August 3rd

In [36]:
racimitos_weight_testing = pd.read_csv('../data/processed/Cultivos/UltimosRacimos/' \
                                 'racimitos-weight_Normalized_TESTING_July-27_August-03.csv', )

In [37]:
print(racimitos_weight_testing.shape)
racimitos_weight_testing.head(10)

(1530, 1)


pesoRacimo
0    0.554054
1    0.337838
2    0.405405
3    0.527027
4    0.337838
5    0.337838
6    0.472973
7    0.513514
8    0.445946
9    0.621622

# 2. Forming the whole Sioma dataset - May 4th to August 3rd - All input variables

We will make a single dataset where all the standardized training data are from:

- Wind Direction
- Luminosity
- Precipitations
- Temperature
- Phreatic Level
- Wind Speed
- Cluster weight of the week from July 27th to August 3rd.

In [38]:
sioma_latest_12_weeks_testing = pd.concat([luminosity_l12w_testing, precipitations_l12w_testing, temperature_l12w_testing, wind_speed_l12w_testing, wind_direction_l12w_testing, phreatic_level_l12w_testing, racimitos_weight_testing], axis=1)
print(sioma_latest_12_weeks_testing.shape)
sioma_latest_12_weeks_testing

(1530, 38)


Luz (lux)  Precipitación (ml)  Temperatura (C)  \
0      0.000000            0.000000         0.045480   
1      0.033142            0.000000         0.241999   
2      0.000000            0.000000         0.171814   
3      0.000000            0.000000         0.687816   
4      0.000000            0.000000         0.895003   
5      0.470816            0.000000         0.154408   
6      0.924321            0.000000         0.203257   
7      0.384545            0.000000         0.498035   
8      0.000000            0.000000         0.701853   
9      0.402236            0.000000         0.410444   
10     0.816791            0.000000         0.090960   
11     0.754968            0.000000         0.154408   
12     0.000000            0.000000         0.179113   
13     0.000000            0.000000         0.572150   
14     0.000000            0.000000         0.642336   
15     0.000000            0.000000         0.463223   
16     0.000000            0.000000         0.241999   
17     0.000000            0.000000         0.820887   
18     0.000000            0.000000         0.129702   
19     0.110377            0.000000         0.719259   
20     0.211909            0.000000         0.104997   
21     0.000000            0.000000         0.108928   
22     0.000000            0.000000         0.129702   
23     0.602927            0.000000         0.828186   
24     0.343659            0.000000         0.122965   
25     0.798626            0.000000         0.115665   
26     0.000000            0.000000         0.435149   
27     0.000000            0.322965         0.221224   
28     0.000000            0.000000         0.747333   
29     0.154680            0.000000         0.140371   
...         ...                 ...              ...   
1500        NaN                 NaN              NaN   
1501        NaN                 NaN              NaN   
1502        NaN                 NaN              NaN   
1503        NaN                 NaN              NaN   
1504        NaN                 NaN              NaN   
1505        NaN                 NaN              NaN   
1506        NaN                 NaN              NaN   
1507        NaN                 NaN              NaN   
1508        NaN                 NaN              NaN   
1509        NaN                 NaN              NaN   
1510        NaN                 NaN              NaN   
1511        NaN                 NaN              NaN   
1512        NaN                 NaN              NaN   
1513        NaN                 NaN              NaN   
1514        NaN                 NaN              NaN   
1515        NaN                 NaN              NaN   
1516        NaN                 NaN              NaN   
1517        NaN                 NaN              NaN   
1518        NaN                 NaN              NaN   
1519        NaN                 NaN              NaN   
1520        NaN                 NaN              NaN   
1521        NaN                 NaN              NaN   
1522        NaN                 NaN              NaN   
1523        NaN                 NaN              NaN   
1524        NaN                 NaN              NaN   
1525        NaN                 NaN              NaN   
1526        NaN                 NaN              NaN   
1527        NaN                 NaN              NaN   
1528        NaN                 NaN              NaN   
1529        NaN                 NaN              NaN   

      Velocidad del viento (Km/h)    E    N   NE   NO    O    S     ...      \
0                        0.121387  0.0  0.0  0.0  0.0  0.0  1.0     ...       
1                        0.027815  0.0  0.0  0.0  0.0  0.0  1.0     ...       
2                        0.017471  0.0  0.0  0.0  0.0  0.0  1.0     ...       
3                        0.016854  0.0  0.0  0.0  1.0  0.0  0.0     ...       
4                        0.000000  0.0  0.0  0.0  0.0  0.0  1.0     ...       
5                        0.063253  0.0  0.0  0.0  1.0  0.0 

## 2.1 Filling **`NaN:`** values
---

We evaluate if `sioma_latest_12_weeks_testing` dataframe has null type `NaN`

Have null values.

In [39]:
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)

# We adjust the values transforming the columns where you need data 
# with the fit() method. 
# We pass the dataframe sioma_28_weeks and 
# with the variables where I can find the empty values, in this case 
# all variables [::] and fit 
imputer = imputer.fit(sioma_latest_12_weeks_testing[::])
sioma_testing_l12w_full_values = imputer.transform(sioma_latest_12_weeks_testing[::])

The previous step generate the ** `sioma_testing_l12w_full_values` ** array which don't have null values

In [40]:
print(sioma_testing_l12w_full_values)
np.isnan(sioma_testing_l12w_full_values)

[[0.         0.         0.04548007 ... 0.32142857 0.         0.55405405]
 [0.03314162 0.         0.24199888 ... 0.90178571 0.93518519 0.33783784]
 [0.         0.         0.17181359 ... 0.61607143 0.78703704 0.40540541]
 ...
 [0.21161292 0.00764122 0.32198905 ... 0.56819988 0.7414466  0.08108108]
 [0.21161292 0.00764122 0.32198905 ... 0.56819988 0.7414466  0.83783784]
 [0.21161292 0.00764122 0.32198905 ... 0.56819988 0.7414466  0.39189189]]


array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [41]:
cols = list(sioma_latest_12_weeks_testing.columns)
print(sioma_latest_12_weeks_testing.shape)
print(sioma_testing_l12w_full_values.shape)
print(cols)

(1530, 38)
(1530, 38)
['Luz (lux)', 'Precipitación (ml)', 'Temperatura (C)', 'Velocidad del viento (Km/h)', 'E', 'N', 'NE', 'NO', 'O', 'S', 'SE', 'SO', 'PORVL2N1', 'PORVL2N2', 'PORVL4N1', 'PORVL5N1', 'PORVL6N1', 'PORVL7N1', 'PORVL8N1', 'PORVL9N1', 'PORVL10N1', 'PORVL13N1', 'PORVL14N1', 'PORVL15N1', 'PORVL16N1', 'PORVL16N2', 'PORVL18N1', 'PORVL18N2', 'PORVL18N3', 'PORVL18N4', 'PORVL21N1', 'PORVL21N2', 'PORVL21N3', 'PORVL21N4', 'PORVL21N5', 'PORVL24N1', 'PORVL24N2', 'pesoRacimo']


In [42]:
# We turn sioma_testing_l12w_full_values to dataframe
sioma_latest_12_weeks_testing_df = pd.DataFrame(data=sioma_testing_l12w_full_values, columns=cols)
print(sioma_latest_12_weeks_testing_df.isnull().any())
print(sioma_latest_12_weeks_testing_df.shape)
sioma_latest_12_weeks_testing_df.head(10)

Luz (lux)                      False
Precipitación (ml)             False
Temperatura (C)                False
Velocidad del viento (Km/h)    False
E                              False
N                              False
NE                             False
NO                             False
O                              False
S                              False
SE                             False
SO                             False
PORVL2N1                       False
PORVL2N2                       False
PORVL4N1                       False
PORVL5N1                       False
PORVL6N1                       False
PORVL7N1                       False
PORVL8N1                       False
PORVL9N1                       False
PORVL10N1                      False
PORVL13N1                      False
PORVL14N1                      False
PORVL15N1                      False
PORVL16N1                      False
PORVL16N2                      False
PORVL18N1                      False
P

Luz (lux)  Precipitación (ml)  Temperatura (C)  \
0   0.000000                 0.0         0.045480   
1   0.033142                 0.0         0.241999   
2   0.000000                 0.0         0.171814   
3   0.000000                 0.0         0.687816   
4   0.000000                 0.0         0.895003   
5   0.470816                 0.0         0.154408   
6   0.924321                 0.0         0.203257   
7   0.384545                 0.0         0.498035   
8   0.000000                 0.0         0.701853   
9   0.402236                 0.0         0.410444   

   Velocidad del viento (Km/h)    E    N   NE   NO    O    S     ...      \
0                     0.121387  0.0  0.0  0.0  0.0  0.0  1.0     ...       
1                     0.027815  0.0  0.0  0.0  0.0  0.0  1.0     ...       
2                     0.017471  0.0  0.0  0.0  0.0  0.0  1.0     ...       
3                     0.016854  0.0  0.0  0.0  1.0  0.0  0.0     ...       
4                     0.000000  0.0  0.0  0.0  0.0  0.0  1.0     ...       
5                     0.063253  0.0  0.0  0.0  1.0  0.0  0.0     ...       
6                     0.000000  0.0  0.0  0.0  0.0  0.0  1.0     ...       
7                     0.017270  1.0  0.0  0.0  0.0  0.0  0.0     ...       
8                     0.033546  0.0  0.0  0.0  0.0  0.0  1.0     ...       
9                     0.000000  1.0  0.0  0.0  0.0  0.0  0.0     ...       

   PORVL18N3  PORVL18N4  PORVL21N1  PORVL21N2  PORVL21N3  PORVL21N4  \
0   0.361905   0.670588   0.447059   0.719626   0.685714   0.540984   
1   0.771429   0.552941   0.764706   0.682243   0.704762   0.598361   
2   0.685714   0.823529   0.576471   0.906542   0.771429   0.803279   
3   0.771429   0.835294   0.623529   0.906542   0.828571   0.754098   
4   0.876190   0.717647   0.717647   0.570093   0.638095   0.786885   
5   0.714286   0.835294   0.670588   0.915888   0.819048   0.762295   
6   0.647954   0.699175   0.647059   0.793048   0.674183   0.631664   
7   0.638095   0.741176   0.447059   1.000000   0.704762   0.614754   
8   0.685714   0.741176   0.764706   0.915888   0.838095   0.811475   
9   0.847619   0.894118   0.729412   0.794393   0.847619   0.762295   

   PORVL21N5  PORVL24N1  PORVL24N2  pesoRacimo  
0   0.644231   0.321429   0.000000    0.554054  
1   0.846154   0.901786   0.935185    0.337838  
2   0.711538   0.616071   0.787037    0.405405  
3   0.807692   0.660714   0.805556    0.527027  
4   0.721154   0.767857   0.787037    0.337838  
5   0.759615   0.660714   0.833333    0.337838  
6   0.528846   0.589286   0.490741    0.472973  
7   0.759615   0.196429   0.833333    0.513514  
8   0.855769   0.991071   0.833333    0.445946  
9   0.759615   0.741071   0.898148    0.621622  

[10 rows x 38 columns]

In [43]:
sioma_latest_12_weeks_testing_df.to_csv('../data/processed/sioma-inputs-output-unified_testing_latest_12_weeks.csv', sep=',', header=True, index=False)
sioma_latest_12_weeks_testing_df.shape

(1530, 38)