In [22]:
from __future__ import unicode_literals

# Importing the libraries
import numpy as np
import pandas as pd

# from sklearn import preprocessing
from sklearn.preprocessing import Imputer

# 1. Reading our pandas dataframes inputs variables

We read our latest 12 weeks life plants input datasets **Phreatic Level, Precipitations, Temperature, Luminosity, Direction and Wind Speed** from May 5th to August 3rd to cover the last 12 weeks of the plant's life (the last 12 of the 28 weeks) which is the time range in which the banana bunch/cluster is formed.


## 1.1. Wind Direction - Training dataset 

In [23]:
wind_direction_l12w_training = pd.read_csv('../data/processed/WindDirection/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Wind-Direction-TRAINING_May-4_August-03_2018_DummiesValues.csv', )

In [24]:
print(wind_direction_l12w_training.shape)
wind_direction_l12w_training.head(10)

(3518, 8)


E  N  NE  NO  O  S  SE  SO
0  0  0   0   0  1  0   0   0
1  0  1   0   0  0  0   0   0
2  1  0   0   0  0  0   0   0
3  1  0   0   0  0  0   0   0
4  0  0   0   0  1  0   0   0
5  0  0   0   0  0  1   0   0
6  1  0   0   0  0  0   0   0
7  0  1   0   0  0  0   0   0
8  0  0   0   0  0  1   0   0
9  0  0   0   0  0  0   0   1

## 1.2. Luminosity - Training dataset 

In [25]:
luminosity_l12w_training = pd.read_csv('../data/processed/Luminosity/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Luminosity_Normalized_TRAINING_May-4_August-03.csv', )

In [26]:
print(luminosity_l12w_training.shape)
luminosity_l12w_training.head(10)

(3518, 1)


Luz (lux)
0   0.455189
1   0.000000
2   0.630661
3   0.000000
4   0.000000
5   0.000000
6   0.000000
7   0.000000
8   0.202594
9   0.000000

## 1.3. Phreatic Level - Training dataset 

In [27]:
phreatic_level_l12w_training = pd.read_csv('../data/processed/PhreaticLevel/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Phreatic-Level_Normalized_TRAINING_May-4_August-03_2018.csv', )

In [28]:
print(phreatic_level_l12w_training.shape)
phreatic_level_l12w_training.head(10)

(1780, 25)


PORVL2N1  PORVL2N2  PORVL4N1  PORVL5N1  PORVL6N1  PORVL7N1  PORVL8N1  \
0  0.455556  0.278261      0.50  0.693182  0.818792  0.753521  0.907563   
1  0.444444  0.191304      0.50  0.693182  0.818792  0.760563  0.907563   
2  0.488889  0.321739      0.68  0.045455  0.657718  0.514085  0.756303   
3  0.244444  0.608696      0.69  0.579545  0.771812  0.302817  0.361345   
4  0.800000  0.860870      0.89  0.818182  0.818792  0.809859  0.890756   
5  0.633333  0.452174      0.69  0.488636  0.536913  0.528169  0.747899   
6  0.766667  0.565217      0.80  0.625000  0.993289  0.753521  0.823529   
7  0.688889  0.652174      0.81  0.590909  0.979866  0.514085  0.747899   
8  0.755556  0.565217      0.83  0.636364  0.664430  0.718310  0.823529   
9  0.633333  0.747826      0.54  0.556818  0.812081  0.767606  0.899160   

   PORVL9N1  PORVL10N1  PORVL13N1    ...      PORVL18N2  PORVL18N3  PORVL18N4  \
0  0.508621   0.827869   0.709091    ...       0.433333   0.674419   0.758621   
1  0.517241   0.827869   0.718182    ...       0.425000   0.682171   0.747126   
2  0.517241   0.942623   0.590909    ...       0.408333   0.674419   0.574713   
3  0.620690   0.770492   0.636364    ...       0.075000   0.589147   0.666667   
4  0.741379   0.786885   0.836364    ...       0.741667   0.759690   0.770115   
5  0.715517   0.663934   0.609091    ...       0.375000   0.519380   0.597701   
6  0.784483   0.639344   0.709091    ...       0.550000   0.511628   0.505747   
7  0.698276   0.631148   0.718182    ...       0.608333   0.627907   0.689655   
8  0.810345   0.631148   0.709091    ...       0.516667   0.503876   0.528736   
9  0.741379   0.827869   0.745455    ...       0.441667   0.705426   0.724138   

   PORVL21N1  PORVL21N2  PORVL21N3  PORVL21N4  PORVL21N5  PORVL24N1  PORVL24N2  
0   0.495495   0.981308   0.712963      0.632   0.809160   0.269565   0.821429  
1   0.495495   0.981308   0.712963      0.632   0.809160   0.252174   0.821429  
2   0.531532   0.774357   0.370370      0.320   0.427481   0.382609   0.767857  
3   0.540541   0.682243   0.675926      0.448   0.656489   0.078261   0.857143  
4   0.738739   0.607477   0.703704      0.704   0.763359   0.391304   0.830357  
5   0.549550   0.598131   0.407407      0.504   0.641221   0.330435   0.625000  
6   0.693694   0.785047   0.629630      0.496   0.801527   0.556522   0.580357  
7   0.576577   0.710280   0.722222      0.576   0.748092   0.469565   0.473214  
8   0.711712   0.700935   0.472222      0.512   0.732824   0.391304   0.669643  
9   0.513514   0.981308   0.703704      0.616   0.801527   0.217391   0.821429  

[10 rows x 25 columns]

## 1.4. Precipitations - Training dataset 

In [29]:
precipitations_l12w_training = pd.read_csv('../data/processed/Precipitations/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Precipitations_Normalized_TRAINING_May-4_August-03.csv', )

In [30]:
print(precipitations_l12w_training.shape)
precipitations_l12w_training.head(10)

(3517, 1)


Precipitación (ml)
0                 0.0
1                 0.0
2                 0.0
3                 0.0
4                 0.0
5                 0.0
6                 0.0
7                 0.0
8                 0.0
9                 0.0

## 1.5. Temperatura - Training dataset 

In [31]:
temperature_l12w_training = pd.read_csv('../data/processed/Temperature/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Temperature_Normalized_TRAINING_May-4_August-03_2018.csv', )

In [32]:
print(temperature_l12w_training.shape)
temperature_l12w_training.head(10)

(3518, 1)


Temperatura (C)
0         0.046610
1         0.331038
2         0.642479
3         0.129237
4         0.589513
5         0.046610
6         0.102754
7         0.082627
8         0.188559
9         0.132415

## 1.6. Wind Speed - Training dataset 

In [33]:
wind_speed_l12w_training = pd.read_csv('../data/processed/WindSpeed/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Wind-Speed_Normalized_TRAINING_May-4_August-03_2018.csv', )

In [34]:
print(wind_speed_l12w_training.shape)
wind_speed_l12w_training.head(10)

(3518, 1)


Velocidad del viento (Km/h)
0                     0.000000
1                     0.021887
2                     0.039084
3                     0.000000
4                     0.000000
5                     0.000000
6                     0.000000
7                     0.021626
8                     0.067442
9                     0.034856

## 1.7. Banana - Cluster weight 

Cluster weight training data of one week of productivity taken as a baseline is loaded.

The week is from July 27th to August 3rd

In [35]:
racimitos_weight_training = pd.read_csv('../data/processed/Cultivos/UltimosRacimos/' \
                                 'racimitos-weight_Normalized_TRAINING_July-27_August-03.csv', )

In [36]:
print(racimitos_weight_training.shape)
racimitos_weight_training.head(10)

(6116, 1)


pesoRacimo
0    0.493524
1    0.207810
2    0.131619
3    0.398286
4    0.388762
5    0.407810
6    0.379238
7    0.426857
8    0.179238
9    0.255429

# 2. Forming the whole Sioma dataset - May 4th to August 3rd - All input variables

We will make a single dataset where all the standardized training data are from:

- Wind Direction
- Luminosity
- Precipitations
- Temperature
- Phreatic Level
- Wind Speed
- Cluster weight of the week from July 27th to August 3rd.

In [37]:
sioma_latest_12_weeks = pd.concat([luminosity_l12w_training, precipitations_l12w_training, temperature_l12w_training, wind_speed_l12w_training, wind_direction_l12w_training, phreatic_level_l12w_training, racimitos_weight_training], axis=1)
print(sioma_latest_12_weeks.shape)
sioma_latest_12_weeks

(6116, 38)


Luz (lux)  Precipitación (ml)  Temperatura (C)  \
0      0.455189            0.000000         0.046610   
1      0.000000            0.000000         0.331038   
2      0.630661            0.000000         0.642479   
3      0.000000            0.000000         0.129237   
4      0.000000            0.000000         0.589513   
5      0.000000            0.000000         0.046610   
6      0.000000            0.000000         0.102754   
7      0.000000            0.000000         0.082627   
8      0.202594            0.000000         0.188559   
9      0.000000            0.000000         0.132415   
10     0.036262            0.000000         0.268008   
11     0.388896            0.000000         0.592691   
12     0.000000            0.000000         0.675318   
13     0.000000            0.000000         0.221928   
14     0.000000            0.000000         0.658898   
15     0.000000            0.000000         0.638771   
16     0.000000            0.000000         0.274894   
17     0.158186            0.000000         0.731462   
18     0.019970            0.000000         0.042903   
19     0.425496            0.000000         0.605932   
20     0.000000            0.000000         0.539725   
21     0.187260            1.000000         0.095869   
22     0.807654            0.000000         0.784428   
23     0.000000            0.000000         0.063030   
24     0.000000            0.000000         0.668962   
25     0.674675            0.000000         0.284958   
26     0.000000            0.052727         0.347458   
27     0.000000            0.000000         0.781250   
28     0.000000            0.000000         0.728284   
29     0.175041            0.000000         0.496822   
...         ...                 ...              ...   
6086        NaN                 NaN              NaN   
6087        NaN                 NaN              NaN   
6088        NaN                 NaN              NaN   
6089        NaN                 NaN              NaN   
6090        NaN                 NaN              NaN   
6091        NaN                 NaN              NaN   
6092        NaN                 NaN              NaN   
6093        NaN                 NaN              NaN   
6094        NaN                 NaN              NaN   
6095        NaN                 NaN              NaN   
6096        NaN                 NaN              NaN   
6097        NaN                 NaN              NaN   
6098        NaN                 NaN              NaN   
6099        NaN                 NaN              NaN   
6100        NaN                 NaN              NaN   
6101        NaN                 NaN              NaN   
6102        NaN                 NaN              NaN   
6103        NaN                 NaN              NaN   
6104        NaN                 NaN              NaN   
6105        NaN                 NaN              NaN   
6106        NaN                 NaN              NaN   
6107        NaN                 NaN              NaN   
6108        NaN                 NaN              NaN   
6109        NaN                 NaN              NaN   
6110        NaN                 NaN              NaN   
6111        NaN                 NaN              NaN   
6112        NaN                 NaN              NaN   
6113        NaN                 NaN              NaN   
6114        NaN                 NaN              NaN   
6115        NaN                 NaN              NaN   

      Velocidad del viento (Km/h)    E    N   NE   NO    O    S     ...      \
0                        0.000000  0.0  0.0  0.0  0.0  1.0  0.0     ...       
1                        0.021887  0.0  1.0  0.0  0.0  0.0  0.0     ...       
2                        0.039084  1.0  0.0  0.0  0.0  0.0  0.0     ...       
3                        0.000000  1.0  0.0  0.0  0.0  0.0  0.0     ...       
4                        0.000000  0.0  0.0  0.0  0.0  1.0  0.0     ...       
5                        0.000000  0.0  0.0  0.0  0.0  0.0 

## 2.1 Filling **`NaN:`** values
---

We evaluate if `sioma_latest_12_weeks` dataframe has null type `NaN`

Have null values.

In [38]:
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)

# We adjust the values transforming the columns where you need data 
# with the fit() method. 
# We pass the dataframe sioma_28_weeks and 
# with the variables where I can find the empty values, in this case 
# all variables [::] and fit 
imputer = imputer.fit(sioma_latest_12_weeks[::])
sioma_training_l12w_full_values = imputer.transform(sioma_latest_12_weeks[::])

The previous step generate the ** `sioma_training_l12w_full_values` ** array which don't have null values

In [39]:
print(sioma_training_l12w_full_values)
np.isnan(sioma_training_l12w_full_values)

[[0.45518872 0.         0.04661017 ... 0.26956522 0.82142857 0.49352381]
 [0.         0.         0.33103814 ... 0.25217391 0.82142857 0.20780952]
 [0.63066124 0.         0.64247881 ... 0.3826087  0.76785714 0.13161905]
 ...
 [0.20511352 0.00369252 0.32616941 ... 0.58389069 0.73893961 0.33161905]
 [0.20511352 0.00369252 0.32616941 ... 0.58389069 0.73893961 0.29352381]
 [0.20511352 0.00369252 0.32616941 ... 0.58389069 0.73893961 0.29352381]]


array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [40]:
cols = list(sioma_latest_12_weeks.columns)
print(sioma_latest_12_weeks.shape)
print(sioma_training_l12w_full_values.shape)
print(cols)

(6116, 38)
(6116, 38)
['Luz (lux)', 'Precipitación (ml)', 'Temperatura (C)', 'Velocidad del viento (Km/h)', 'E', 'N', 'NE', 'NO', 'O', 'S', 'SE', 'SO', 'PORVL2N1', 'PORVL2N2', 'PORVL4N1', 'PORVL5N1', 'PORVL6N1', 'PORVL7N1', 'PORVL8N1', 'PORVL9N1', 'PORVL10N1', 'PORVL13N1', 'PORVL14N1', 'PORVL15N1', 'PORVL16N1', 'PORVL16N2', 'PORVL18N1', 'PORVL18N2', 'PORVL18N3', 'PORVL18N4', 'PORVL21N1', 'PORVL21N2', 'PORVL21N3', 'PORVL21N4', 'PORVL21N5', 'PORVL24N1', 'PORVL24N2', 'pesoRacimo']


In [41]:
# We turn sioma_training_l12w_full_values to dataframe
sioma_latest_12_weeks_training_df = pd.DataFrame(data=sioma_training_l12w_full_values, columns=cols)
print(sioma_latest_12_weeks_training_df.isnull().any())
sioma_latest_12_weeks_training_df.head(10)

Luz (lux)                      False
Precipitación (ml)             False
Temperatura (C)                False
Velocidad del viento (Km/h)    False
E                              False
N                              False
NE                             False
NO                             False
O                              False
S                              False
SE                             False
SO                             False
PORVL2N1                       False
PORVL2N2                       False
PORVL4N1                       False
PORVL5N1                       False
PORVL6N1                       False
PORVL7N1                       False
PORVL8N1                       False
PORVL9N1                       False
PORVL10N1                      False
PORVL13N1                      False
PORVL14N1                      False
PORVL15N1                      False
PORVL16N1                      False
PORVL16N2                      False
PORVL18N1                      False
P

Luz (lux)  Precipitación (ml)  Temperatura (C)  \
0   0.455189                 0.0         0.046610   
1   0.000000                 0.0         0.331038   
2   0.630661                 0.0         0.642479   
3   0.000000                 0.0         0.129237   
4   0.000000                 0.0         0.589513   
5   0.000000                 0.0         0.046610   
6   0.000000                 0.0         0.102754   
7   0.000000                 0.0         0.082627   
8   0.202594                 0.0         0.188559   
9   0.000000                 0.0         0.132415   

   Velocidad del viento (Km/h)    E    N   NE   NO    O    S     ...      \
0                     0.000000  0.0  0.0  0.0  0.0  1.0  0.0     ...       
1                     0.021887  0.0  1.0  0.0  0.0  0.0  0.0     ...       
2                     0.039084  1.0  0.0  0.0  0.0  0.0  0.0     ...       
3                     0.000000  1.0  0.0  0.0  0.0  0.0  0.0     ...       
4                     0.000000  0.0  0.0  0.0  0.0  1.0  0.0     ...       
5                     0.000000  0.0  0.0  0.0  0.0  0.0  1.0     ...       
6                     0.000000  1.0  0.0  0.0  0.0  0.0  0.0     ...       
7                     0.021626  0.0  1.0  0.0  0.0  0.0  0.0     ...       
8                     0.067442  0.0  0.0  0.0  0.0  0.0  1.0     ...       
9                     0.034856  0.0  0.0  0.0  0.0  0.0  0.0     ...       

   PORVL18N3  PORVL18N4  PORVL21N1  PORVL21N2  PORVL21N3  PORVL21N4  \
0   0.674419   0.758621   0.495495   0.981308   0.712963      0.632   
1   0.682171   0.747126   0.495495   0.981308   0.712963      0.632   
2   0.674419   0.574713   0.531532   0.774357   0.370370      0.320   
3   0.589147   0.666667   0.540541   0.682243   0.675926      0.448   
4   0.759690   0.770115   0.738739   0.607477   0.703704      0.704   
5   0.519380   0.597701   0.549550   0.598131   0.407407      0.504   
6   0.511628   0.505747   0.693694   0.785047   0.629630      0.496   
7   0.627907   0.689655   0.576577   0.710280   0.722222      0.576   
8   0.503876   0.528736   0.711712   0.700935   0.472222      0.512   
9   0.705426   0.724138   0.513514   0.981308   0.703704      0.616   

   PORVL21N5  PORVL24N1  PORVL24N2  pesoRacimo  
0   0.809160   0.269565   0.821429    0.493524  
1   0.809160   0.252174   0.821429    0.207810  
2   0.427481   0.382609   0.767857    0.131619  
3   0.656489   0.078261   0.857143    0.398286  
4   0.763359   0.391304   0.830357    0.388762  
5   0.641221   0.330435   0.625000    0.407810  
6   0.801527   0.556522   0.580357    0.379238  
7   0.748092   0.469565   0.473214    0.426857  
8   0.732824   0.391304   0.669643    0.179238  
9   0.801527   0.217391   0.821429    0.255429  

[10 rows x 38 columns]

In [42]:
sioma_latest_12_weeks_training_df.to_csv('../data/processed/sioma-inputs-output-unified_training_latest_12_weeks.csv', sep=',', header=True, index=False)
sioma_latest_12_weeks_training_df.shape

(6116, 38)