In [26]:
from __future__ import unicode_literals

import pandas as pd
import numpy as np

# 1. Reading our pandas dataframes inputs variables

We read our latest 12 weeks life plants input datasets **Phreatic Level, Precipitations, Temperature, Luminosity, Direction and Wind Speed** 

## 1.1. Reading Wind Direction - Raw dataset 

In [27]:
wind_direction_l12w = pd.read_csv('../data/raw/FincaPorvenir/Metereologico/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Direccion-del-viento_May-4_August-03_2018.csv', )

In [28]:
print(wind_direction_l12w.shape)
wind_direction_l12w.head()

# Checking null values
print(wind_direction_l12w.isnull().any())
print(wind_direction_l12w.isnull().values.any())

# Selecting relevant index columns features
wind_direction_l12w_pos = wind_direction_l12w.iloc[:, 1].values

print(type(wind_direction_l12w_pos))
# When we use iloc() dataframe function, the variable is turned on numpy array

wind_direction_l12w_pos

(4398, 2)
Fecha:                        False
Direccion del viento (Pos)    False
dtype: bool
False
<class 'numpy.ndarray'>


array(['SO', 'SO', 'SO', ..., 'SE', 'S', 'SE'], dtype=object)

In [29]:
# Creating dataframe to concatenate more later
col=['Direccion del viento (Pos)']
wind_direction_l12w_pos_df = pd.DataFrame(wind_direction_l12w_pos, columns=col)
print(type(wind_direction_l12w_pos_df))
print("The dimensionality of wind_direction dataframe is: " +'\n' , wind_direction_l12w_pos_df.shape)
wind_direction_l12w_pos_df.head()

wind_direction_l12w_pos_df.to_csv('../data/interim/ComposeRawDataset/Lates-t12-weeks/wind_direction_l12w.csv', sep=',', header=True, index=True)

<class 'pandas.core.frame.DataFrame'>
The dimensionality of wind_direction dataframe is: 
 (4398, 1)


## 1.2. Reading Luminosity - Raw dataset 

In [30]:
luminosity_lw12 = pd.read_csv('../data/raw/FincaPorvenir/Metereologico/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Luz_May-4_August-03_2018.csv', )

In [31]:
print(luminosity_lw12.shape)
luminosity_lw12.head()

# Checking null values
print(luminosity_lw12.isnull().any())
print(luminosity_lw12.isnull().values.any())

# Selecting relevant index columns features
luminosity_lw12_luxes = luminosity_lw12.iloc[:, 1].values

print(type(luminosity_lw12_luxes))
# When we use iloc() dataframe function, the variable is turned on numpy array

luminosity_lw12_luxes

(4398, 2)
Fecha:       False
Luz (lux)    False
dtype: bool
False
<class 'numpy.ndarray'>


array([1, 1, 1, ..., 1, 1, 1])

In [32]:
# Creating dataframe to concatenate more later
col=['Luz (lux)']
luminosity_luxes_df = pd.DataFrame(luminosity_lw12_luxes, columns=col)
print(type(luminosity_luxes_df))
print("The dimensionality of wind_direction dataframe is: " +'\n' , luminosity_luxes_df.shape)
luminosity_luxes_df.head()

luminosity_luxes_df.to_csv('../data/interim/ComposeRawDataset/Lates-t12-weeks/luminosity_l12w.csv', sep=',', header=True, index=True)

<class 'pandas.core.frame.DataFrame'>
The dimensionality of wind_direction dataframe is: 
 (4398, 1)


## 1.3 Reading phreatic level - Raw dataset 

### 1.3.1 Loading phreatic level - Raw dataset - From May 5 to August 03

In [33]:
phreatic_level_l12w = pd.read_csv('../data/raw/FincaPorvenir/Drenajes/DatosNivelFreatico/Latest_12-weeks_May-4_August-03_2018/' \
                                 'From_2018-05-04_00-00-00_To_2018-08-03_23-59-59.csv', )

In [34]:
print("THE DIMENSIONALITY IS: " +'\n')
print(phreatic_level_l12w.shape)
# Numero de columnas
print("Columns number", len(phreatic_level_l12w.columns))
# Numero de registros de la columna PORVL10N1
print("PORVL10N1 column rows number",len(phreatic_level_l12w.PORVL10N1))
phreatic_level_l12w.head()

THE DIMENSIONALITY IS: 

(2226, 76)
Columns number 76
PORVL10N1 column rows number 2226


Fecha      Hora  PORVL2N1     Fecha.1    Hora.1  PORVL2N2     Fecha.2  \
0  2018-05-04  01:01:35      0.65  2018-05-04  01:59:54      0.57  2018-05-04   
1  2018-05-04  02:01:34      0.66  2018-05-04  02:59:55      0.59  2018-05-04   
2  2018-05-04  03:01:36      0.68  2018-05-04  03:59:55      0.60  2018-05-04   
3  2018-05-04  04:02:05      0.69  2018-05-04  04:59:55      0.61  2018-05-04   
4  2018-05-04  05:01:35      0.70  2018-05-04  05:59:55      0.62  2018-05-04   

     Hora.2  PORVL4N1     Fecha.3    ...    PORVL21N4    Fecha.22   Hora.22  \
0  01:22:55      0.76  2018-05-04    ...         0.73  2018-05-04  01:04:23   
1  02:22:55      0.78  2018-05-04    ...         0.74  2018-05-04  02:04:16   
2  03:22:54      0.79  2018-05-04    ...         0.75  2018-05-04  03:04:20   
3  04:22:55      0.80  2018-05-04    ...         0.76  2018-05-04  04:04:19   
4  05:22:55      0.81  2018-05-04    ...         0.77  2018-05-04  05:04:18   

  PORVL21N5    Fecha.23   Hora.23 PORVL24N1    Fecha.24   Hora.24 PORVL24N2  
0      0.88  2018-05-04  01:16:08      0.64  2018-05-04  01:19:34      0.94  
1      0.89  2018-05-04  02:17:17      0.54  2018-05-04  02:19:34      0.95  
2      0.90  2018-05-04  03:15:58      0.54  2018-05-04  03:20:13      0.97  
3      0.91  2018-05-04  04:16:00      0.55  2018-05-04  04:19:35      0.98  
4      0.92  2018-05-04  05:15:58      0.55  2018-05-04  05:19:36      0.99  

[5 rows x 76 columns]

In [35]:
## 1.3.2. Selecting  relevant index columns features
# ---
phreatic_level_lots_nodes_l12w = phreatic_level_l12w.filter(regex=('PORVL.*'))
phreatic_level_lots_nodes_l12w.head()

phreatic_level_lots_nodes_l12w.to_csv('../data/interim/ComposeRawDataset/Lates-t12-weeks/phreatic_level_l12w.csv', sep=',', header=True, index=True)

## 1.4.Reading precipitations - Raw dataset 

In [36]:
precipitations_l12w_df = pd.read_csv('../data/raw/FincaPorvenir/Metereologico/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Precipitacion_May-4_August-03_2018.csv', )

In [37]:
print(precipitations_l12w_df.shape)
precipitations_l12w_df.head()

# Selecting relevant index columns features
precipitations_l12w_raw_array = precipitations_l12w_df.iloc[:, 1].values
# Rehape the array 
precipitations_l12w_raw_array = precipitations_l12w_raw_array.reshape(-1, 1)
precipitations_l12w_raw_array

# Compose a dataframe
col=['Precipitación (ml)']
precipitations_lw12_raw_df = pd.DataFrame(precipitations_l12w_raw_array, columns=col)
print(type(precipitations_lw12_raw_df))
print("The dimensionality of wind_direction dataframe is: " +'\n' , precipitations_lw12_raw_df.shape)
precipitations_lw12_raw_df.head()

precipitations_lw12_raw_df.to_csv('../data/interim/ComposeRawDataset/Lates-t12-weeks/precipitations.csv', sep=',', header=True, index=True)

(4397, 2)
<class 'pandas.core.frame.DataFrame'>
The dimensionality of wind_direction dataframe is: 
 (4397, 1)


## 1.5 Reading temperature - Raw dataset 

In [38]:
temperature_l12w = pd.read_csv('../data/raw/FincaPorvenir/Metereologico/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Temperatura_May-4_August-03_2018.csv', )

In [39]:
print(temperature_l12w.shape)
temperature_l12w.head()

(4398, 2)


Fecha:  Temperatura (C)
0  2018-05-04 00:07:38            23.75
1  2018-05-04 00:37:39            23.68
2  2018-05-04 01:07:38            23.68
3  2018-05-04 01:37:39            23.56
4  2018-05-04 02:07:39            23.50

In [40]:
temperature_l12w_array = temperature_l12w.iloc[:,1].values
temperature_l12w_array = temperature_l12w_array.reshape(-1, 1)
temperature_l12w_array

array([[23.75],
       [23.68],
       [23.68],
       ...,
       [23.81],
       [23.5 ],
       [23.62]])

In [41]:
# Compose a dataframe
col=['Temperatura (C)']
temperature_lw12_raw_df = pd.DataFrame(temperature_l12w_array, columns=col)
print(type(temperature_lw12_raw_df))
print("The dimensionality of wind_direction dataframe is: " +'\n' , temperature_lw12_raw_df.shape)
temperature_lw12_raw_df.head()

temperature_lw12_raw_df.to_csv('../data/interim/ComposeRawDataset/Lates-t12-weeks/temperature.csv', sep=',', header=True, index=True)

<class 'pandas.core.frame.DataFrame'>
The dimensionality of wind_direction dataframe is: 
 (4398, 1)


## 1.6 Reading wind speed - Raw dataset

In [46]:
wind_speed_l12w = pd.read_csv('../data/raw/FincaPorvenir/Metereologico/Latest_12-weeks_May-4_August-03_2018/' \
                                 'Velocidad-del-viento_May-4_August-03_2018.csv', )

In [47]:
print(wind_speed_l12w.shape)
wind_speed_l12w.head()



(4398, 2)


Fecha:  Velocidad del viento (Km/h)
0  2018-05-04 00:07:38                          0.0
1  2018-05-04 00:37:39                          0.0
2  2018-05-04 01:07:38                          0.0
3  2018-05-04 01:37:38                          0.0
4  2018-05-04 02:07:38                          0.0

In [48]:
wind_speed_l12w_array = wind_speed_l12w.iloc[:,1].values

# Rehape the array 
wind_speed_l12w_array = wind_speed_l12w_array.reshape(-1, 1)
wind_speed_l12w_array

array([[0.        ],
       [0.        ],
       [0.        ],
       ...,
       [0.        ],
       [0.        ],
       [4.21052632]])

In [49]:
# Compose a dataframe
col=['Velocidad del viento (Km/h)']
wind_speed_lw12_raw_df = pd.DataFrame(wind_speed_l12w_array, columns=col)
print(type(wind_speed_lw12_raw_df))
print("The dimensionality of wind_direction dataframe is: " +'\n' , wind_speed_lw12_raw_df.shape)
wind_speed_lw12_raw_df.head()

wind_speed_lw12_raw_df.to_csv('../data/interim/ComposeRawDataset/Lates-t12-weeks/wind-speed.csv', sep=',', header=True, index=True)

<class 'pandas.core.frame.DataFrame'>
The dimensionality of wind_direction dataframe is: 
 (4398, 1)


## 1.7 Reading Racimitos Weight - Raw dataset

In [50]:
racimitos_raw = pd.read_csv('../data/interim/Cultivos/UltimosRacimos/racimitos-27July_To_03August-SQL-JoinedData.csv')

In [51]:
print(racimitos_raw.shape)
racimitos_raw.head()

(7646, 7)


peso                fecha  nombreLote  numeroLote       lat        lng  \
0  23.09  2018-07-27 07:08:58           5           5  7.766231 -76.762676   
1  30.50  2018-07-27 07:09:01           5           5  7.766231 -76.762676   
2  19.50  2018-07-27 07:09:02           5           5  7.766231 -76.762676   
3  25.50  2018-07-27 07:09:04           5           5  7.766231 -76.762676   
4  26.50  2018-07-27 07:09:06           5           5  7.766231 -76.762676   

  nombreFinca  
0    Porvenir  
1    Porvenir  
2    Porvenir  
3    Porvenir  
4    Porvenir

In [53]:
racimitosPorvenir_raw = racimitos_raw[['peso']]
print(racimitosPorvenir_raw.shape)
racimitosPorvenir_raw.head()

racimitosPorvenir_raw.to_csv('../data/interim/ComposeRawDataset/Lates-t12-weeks/racimitos.csv', sep=',', header=True, index=True)

(7646, 1)
